name: Build and Deploy to aws-lambda

on:
  release:
    types: [published]

jobs:
  Deploy:
    name: 'Installing, Building, and Deploying Function'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Installing, and Deploying Function"
        run: |
          pwd
          for fun in poc ; do
            echo ${fun}
            cd ${fun}

            if [[ -f "serverless.yml" ]]; then
              echo "Creating Zip"
              zip -j deploy.zip ./*

              echo "Deploying Lambda"
              aws lambda update-function-code --function-name=${fun} --zip-file=fileb://deploy.zip

              echo "${fun} Deployed."
            fi

            cd ..
          done
